/**
 * ⚠️ SINGLE SOURCE of this site's machine-readable identity (llms.txt,
 * JSON-LD, default meta description). Generated by create-inceptor-app —
 * the TODO below is yours to resolve before shipping.
 */
export const SITE = {
  name: 'Banxico Watch',
  // TODO(agent): replace with Banxico Watch's real one-line positioning. This is
  // what search engines and LLM crawlers will quote about the site.
  description: 'Banxico Watch — built on the Inceptor issue-driven scaffold.',
  repoSlug: (import.meta.env.PUBLIC_REPO_SLUG as string | undefined) ?? 'ArtemioPadilla/banxico-watch',
  license: 'MIT',
} as const;

export const REPO_URL = `https://github.com/${SITE.repoSlug}`;
